# Generated by Django 6.0.4 on 2026-09-29 20:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id_transportadora', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_unidade_sigor', models.CharField(help_text='Código da Unidade no SIGOR/CETESB', max_length=50)),
                ('is_homologada', models.BooleanField(default=False)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_transportadora', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id_motorista', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(help_text='Nome exato conforme documento (Regra SIGOR)', max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cnh', models.CharField(max_length=20, unique=True)),
                ('is_ativo', models.BooleanField(default=True)),
                ('funcionario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dados_motorista', to='empresas.funcionario')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motoristas', to='transportes.transportadora')),
            ],
        ),
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('id_caminhao', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='A placa deve conter exatamente 7 caracteres alfanuméricos, sem hífen.', regex='^[a-zA-Z0-9]{7}$')])),
                ('capacidade_carga_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_ativo', models.BooleanField(default=True)),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caminhoes', to='transportes.transportadora')),
            ],
        ),
    ]
