import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone
import transportes.models.fretes


class Migration(migrations.Migration):
    dependencies = [
        ("anuncios", "0008_alter_anuncio_imagem_url"),
        ("transportes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transportadora",
            name="codigo_unidade_sigor",
            field=models.CharField(blank=True, help_text="Código da unidade no SIGOR/CETESB", max_length=50),
        ),
        migrations.AddField(model_name="transportadora", name="registro_antt", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="transportadora", name="tipo_transporte", field=models.CharField(blank=True, choices=[("fracionado", "Fracionado"), ("carga_fechada", "Carga fechada"), ("roll_on", "Roll-on / caçamba"), ("dedicado", "Dedicado")], max_length=24)),
        migrations.AddField(model_name="transportadora", name="regioes_atendidas", field=models.CharField(blank=True, max_length=300)),
        migrations.AddField(model_name="transportadora", name="tamanho_frota", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="transportadora", name="custos_por_km", field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name="transportadora", name="status_sigor", field=models.CharField(choices=[("nao_validado", "Não validado"), ("validando", "Em validação"), ("validado", "Validado"), ("invalido", "Inválido")], default="nao_validado", max_length=20)),
        migrations.AddField(model_name="transportadora", name="transportadora_sugerida", field=models.CharField(blank=True, max_length=300)),
        migrations.AddField(model_name="transportadora", name="validado_em", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="transportadora", name="criado_em", field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now), preserve_default=False),
        migrations.AddField(model_name="transportadora", name="atualizado_em", field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now), preserve_default=False),
        migrations.AlterModelOptions(name="transportadora", options={"ordering": ["empresa__razao_social"]}),
        migrations.AlterField(
            model_name="caminhao",
            name="placa",
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message="A placa deve ter 7 caracteres alfanuméricos.", regex="^[a-zA-Z0-9]{7}$")]),
        ),
        migrations.AddField(model_name="caminhao", name="tipo_veiculo", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="caminhao", name="capacidade_volume_m3", field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
        migrations.AddField(model_name="caminhao", name="criado_em", field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now), preserve_default=False),
        migrations.AlterModelOptions(name="caminhao", options={"ordering": ["placa"]}),
        migrations.AlterField(model_name="motorista", name="nome_completo", field=models.CharField(help_text="Nome exato conforme documento", max_length=150)),
        migrations.AddField(model_name="motorista", name="categoria_cnh", field=models.CharField(blank=True, max_length=5)),
        migrations.AddField(model_name="motorista", name="validade_cnh", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="motorista", name="telefone", field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name="motorista", name="criado_em", field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now), preserve_default=False),
        migrations.AlterModelOptions(name="motorista", options={"ordering": ["nome_completo"]}),
        migrations.CreateModel(
            name="ProcessoFrete",
            fields=[
                ("id_processo_frete", models.BigAutoField(primary_key=True, serialize=False)),
                ("numero_pedido", models.CharField(max_length=50, unique=True)),
                ("cliente", models.CharField(max_length=150)),
                ("material", models.CharField(max_length=120)),
                ("origem", models.CharField(max_length=180)),
                ("destino", models.CharField(max_length=180)),
                ("cubagem_m3", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("peso_ton", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("data_pedido", models.DateField(default=django.utils.timezone.localdate)),
                ("previsao_entrega", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("awaiting_quote", "Aguardando cotação"), ("quoting", "Em cotação"), ("awaiting_document", "Aguardando documento"), ("transport", "Em transporte"), ("divergent", "Divergente"), ("delivered", "Entregue"), ("cancelled", "Cancelado")], default="awaiting_quote", max_length=24)),
                ("fonte", models.CharField(choices=[("erp", "ERP"), ("manual", "Manual"), ("marketplace", "Marketplace")], default="manual", max_length=15)),
                ("modalidade", models.CharField(choices=[("quote", "Cotação"), ("contracted", "Transportadora contratada"), ("customer_pickup", "Retirada pelo cliente")], default="quote", max_length=20)),
                ("motivo_sem_cotacao", models.CharField(blank=True, max_length=300)),
                ("quantidade_embalagens", models.PositiveIntegerField(default=0)),
                ("dimensoes_caixa_cm", models.JSONField(blank=True, default=dict)),
                ("arquivo_nfe", models.CharField(blank=True, max_length=255)),
                ("registro_coleta", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("anuncio", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processos_frete", to="anuncios.anuncio")),
                ("empresa_solicitante", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="processos_frete", to="empresas.empresa")),
            ],
            options={"ordering": ["-criado_em"]},
        ),
        migrations.CreateModel(
            name="OportunidadeFrete",
            fields=[
                ("id_oportunidade", models.BigAutoField(primary_key=True, serialize=False)),
                ("valor_sugerido", models.DecimalField(decimal_places=2, max_digits=12)),
                ("janela_coleta", models.CharField(max_length=180)),
                ("tipo_veiculo", models.CharField(max_length=100)),
                ("observacoes", models.CharField(blank=True, max_length=500)),
                ("status", models.CharField(choices=[("open", "Aberta"), ("sent", "Com propostas"), ("recommended", "Recomendada"), ("closed", "Encerrada"), ("cancelled", "Cancelada")], default="open", max_length=15)),
                ("score_ambiental", models.PositiveSmallIntegerField(default=0)),
                ("publicada_em", models.DateTimeField(auto_now_add=True)),
                ("encerrada_em", models.DateTimeField(blank=True, null=True)),
                ("processo", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="oportunidade", to="transportes.processofrete")),
            ],
            options={"ordering": ["-publicada_em"]},
        ),
        migrations.CreateModel(
            name="PropostaFrete",
            fields=[
                ("id_proposta", models.BigAutoField(primary_key=True, serialize=False)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("prazo_entrega_dias", models.PositiveIntegerField(default=1)),
                ("observacao", models.CharField(blank=True, max_length=500)),
                ("status", models.CharField(choices=[("sent", "Enviada"), ("approved", "Aprovada"), ("rejected", "Recusada"), ("cancelled", "Cancelada")], default="sent", max_length=15)),
                ("enviada_em", models.DateTimeField(auto_now_add=True)),
                ("respondida_em", models.DateTimeField(blank=True, null=True)),
                ("oportunidade", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="propostas", to="transportes.oportunidadefrete")),
                ("transportadora", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="propostas_frete", to="transportes.transportadora")),
            ],
            options={"ordering": ["valor", "prazo_entrega_dias"]},
        ),
        migrations.AddConstraint(model_name="propostafrete", constraint=models.UniqueConstraint(fields=("oportunidade", "transportadora"), name="unique_carrier_freight_bid")),
        migrations.CreateModel(
            name="DocumentoFrete",
            fields=[
                ("id_documento", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome_arquivo", models.CharField(max_length=255)),
                ("numero_cte", models.CharField(max_length=80, unique=True)),
                ("valor_cte", models.DecimalField(decimal_places=2, max_digits=12)),
                ("recebido_em", models.DateTimeField(auto_now_add=True)),
                ("processo", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="documento", to="transportes.processofrete")),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoFrete",
            fields=[
                ("id_historico", models.BigAutoField(primary_key=True, serialize=False)),
                ("autor", models.CharField(max_length=150)),
                ("evento", models.CharField(default="observacao", max_length=80)),
                ("observacao", models.CharField(max_length=1000)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("processo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historico", to="transportes.processofrete")),
            ],
            options={"ordering": ["-criado_em"]},
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                ("id_entrega", models.BigAutoField(primary_key=True, serialize=False)),
                ("endereco", models.CharField(max_length=250)),
                ("cidade", models.CharField(max_length=120)),
                ("previsao", models.DateTimeField(blank=True, null=True)),
                ("numero_nfe", models.CharField(blank=True, max_length=80)),
                ("token_qr", models.CharField(default=transportes.models.fretes.gerar_token_entrega, editable=False, max_length=64, unique=True)),
                ("nome_recebedor_autorizado", models.CharField(max_length=150)),
                ("cpf_recebedor_autorizado", models.CharField(max_length=14)),
                ("status", models.CharField(choices=[("pending", "Aguardando saída"), ("route", "Em rota"), ("delivered", "Entregue"), ("cancelled", "Cancelada")], default="pending", max_length=15)),
                ("nome_recebedor", models.CharField(blank=True, max_length=150)),
                ("cpf_recebedor", models.CharField(blank=True, max_length=14)),
                ("assinatura", models.TextField(blank=True)),
                ("tipo_recebimento", models.CharField(choices=[("complete", "Completo"), ("with_reservation", "Com ressalva")], default="complete", max_length=20)),
                ("ressalva", models.CharField(blank=True, max_length=1000)),
                ("confirmada_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("caminhao", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="entregas", to="transportes.caminhao")),
                ("motorista", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="entregas", to="transportes.motorista")),
                ("processo", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="entrega", to="transportes.processofrete")),
                ("transportadora", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="entregas", to="transportes.transportadora")),
            ],
            options={"ordering": ["previsao", "id_entrega"]},
        ),
    ]
