# Generated by Django 6.0.4 on 2026-05-04 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0005_alter_produto_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('preco_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('status_anuncio', models.CharField(default='', max_length=1)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('descricao_especifica', models.CharField(blank=True, max_length=500)),
                ('nr_qtd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_final', models.DateField(blank=True)),
                ('produto', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='produto', to='produtos.produto')),
            ],
        ),
    ]
