# Generated by Django 6.0.4 on 2026-05-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_reserva_prazo_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagem_url',
            field=models.URLField(blank=True),
        ),
    ]
