# Generated by Django 6.0.4 on 2026-05-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_alter_anuncio_imagem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='descricao_especifica',
            field=models.CharField(blank=True),
        ),
    ]
