# Generated by Django 6.0.4 on 2026-05-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_alter_anuncio_descricao_especifica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='descricao_especifica',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
