# Generated by Django 6.0.3 on 2026-04-04 18:37

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.CharField(primary_key=True, serialize=False)),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=100)),
                ('telefone_whatsapp', models.CharField(max_length=20)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('descricao_segmento', models.CharField(blank=True, max_length=60)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
