# Generated by Django 6.0.3 on 2026-04-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_id_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefone_whatsapp',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
