# Generated by Django 6.0.3 on 2026-04-07 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_telefone_whatsapp'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estoque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='estoque', to='estoque.estoque'),
        ),
    ]
