# Generated by Django 6.0.3 on 2026-04-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_empresa_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='estoque',
        ),
    ]
