# Generated by Django 6.0.4 on 2026-04-27 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_produto', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=1)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('descricao_produto', models.CharField(max_length=256)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='empresas.empresa')),
            ],
        ),
    ]
