# Generated by Django 6.0.3 on 2026-04-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_produto', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=1)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('descricao_produto', models.CharField(max_length=256)),
            ],
        ),
    ]
